"use strict";
// lang-pt.ts
Object.defineProperty(exports, "__esModule", { value: true });
exports.LANG_EN_NAME = 'en';
exports.LANG_EN_TRANS = {
    'PF': 'Physical person',
    'PJ': 'Legal person',
    'true': 'Yes',
    'false': 'No',
    'common-msg-success-header': 'Success',
    'common-msg-info-header': 'Information',
    'common-msg-warn-header': 'Notice',
    'common-msg-error-header': 'Error',
    'common-msg-success': 'Execution ok',
    'common-msg-info': 'Access denied',
    'common-msg-warn': 'Business error',
    'common-msg-error': 'Internal error',
    'common-msg-403': 'Access denied',
    'login_lb_title': 'Title login',
    'login-lb-user': 'User',
    'login-lb-password': 'Password',
    'msg-error-login': 'You need to fill in the user field',
    'msg-error-password': 'You need to fill in the password field',
    'btn-new-simulation': 'New simulation',
    'btn-my-proposals': 'My proposals',
    'btn-login': 'Login',
    'btn-my-profile': 'Profile',
    'btn-administration': 'Management',
    'btn-insurance': 'Insurance',
    'lb-change-password': 'Change password',
    'lb-password-field-required-size': 'Required field! (minimum 6 characters)',
    'lb-current-password': 'Current password',
    'lb-new-password': 'New password',
    'lb-confirm-password': 'Password confirmation',
    'btn-notifications': 'Notifications',
    'lb-notifications': 'Notifications',
    'btn-change-brand': 'Change brand',
    'lb-all-notification': 'View all notifications',
    'msg-not-connected': 'Not connected',
    'btn-edit': 'To edit',
    'btn-save': 'To save',
    'btn-clear': 'To clean',
    'btn-delete': 'Delete',
    'btn-continue': 'Continue',
    'lb-password-field-required': 'Field not filled.',
    'lk-forgot-password': 'I forgot my password',
    'lb-forgot-password': 'I forgot my password',
    'forgot-password-lb-useremail': 'User / email',
    'forgot-password-msg': 'Inform your user or email address to receive an email with the link to create the new password',
    'lb-news': 'News',
    'lb-support': 'Support',
    'lb-help-desk': 'To report problems or questions, contact the system help desk.',
    'lb-phone-help-desk': 'Help desk phone',
    'lb-email-support': 'Support email',
    'btn-deactivation-of-services': 'Deactivation of services',
    'btn-services-configuration': 'Service configuration',
    'btn-services-configuration-required': 'Required service configuration',
    'btn-dealer-proposal': 'Concession dealer proposals',
    'btn-required': 'Required',
    'btn-commission-level': 'Release of return',
    'btn-submission-process-configuration': 'Submission process configuration',
    'btn-proposal-update': 'Proposal update',
    'btn-news-administration': 'News & events',
    'btn-promotional-images': 'Promotional images',
    'lb-promotional-images': 'Promotional images',
    'btn-models': 'Models',
    'msg-image-size': 'The image must have the minimum dimensions of 1024x435 px and maximum size of 8mb.',
    'lb-select-brand': 'Select brand',
    'msg-error-extension': 'Only files with the following extensions are allowed',
    'msg-error-max-size': 'The image must have a maximum size of 8mb.',
    'msg-sucesso-save-image': 'Image saved successfully.',
    'msg-sucesso-remove-image': 'Image successfully removed.',
    'msg-info-select-financi-brand': 'You must select a Financial Mark.',
    'lb-avaliable-services': 'Available services',
    'lb-avaliable-service': 'Service available',
    'lb-service-unavaliable': 'Service unavailable',
    'lb-dealerships': 'Real estate agencies',
    'lb-avaliable': 'Available',
    'lb-not-avaliable': 'Not available',
    'lb-mandatory-services': 'Required services',
    'lb-required': 'Required',
    'lb-not-required': 'Not obligatory',
    'lb-check-with-RCI-comercial-consultant': 'Check with rci commercial consultant',
    'lb-brand': 'Brand',
    'btn-choose-file': 'Choose file',
    'btn-remove': 'To remove',
    'lb-vehicle-band': 'Vehicle brand',
    'lb-vehicle-model': 'Vehicle model',
    'lb-vehicle-version': 'Vehicle version',
    'lb-version': 'Version',
    'msg-image-size-modelo': 'Image with size above allowed. \ n choose a file smaller than 2 mb',
    'msg-images-registered-brand': 'There are no images registered for the brand',
    'msg-images-registered-model': 'There are no images registered for the model',
    'msg-images-registered-version': 'There are no images registered for the version',
    'update-button-behavior-configuration': 'Update button behavior setting',
    'lb-welcome': 'Welcome',
    'lb-connected-by': 'Connected as',
    'lb-back-your-profile': 'Back to your profile',
    'btn-search': 'Search',
    'btn-reset': 'Reset',
    'btn-enter': 'Get in',
    'lb-proposal-number': 'Proposal number',
    'lb-customer-type': 'Customer type',
    'btn-logout': 'Get out',
    'btn-send': 'To send',
    'lb-my-agreements': 'My proposals',
    'lb-client-type': 'Customer type',
    'lb-status-proposal': 'Proposal status',
    'lb-date-initial-creation': 'Initial creation date',
    'lb-date-final-creation': 'Date final creation',
    'lb-date-initial-validate': 'Initial validity date',
    'lb-date-final-validate': 'Date final validity',
    'lb-dealership': 'Concessionaire',
    'lb-exemption': 'Exemption',
    'lb-with': 'With',
    'lb-of': 'In',
    'lb-custumer-personal-data': 'Customer personal data',
    'lb-cpf-cnpj': 'Cpf or cnpj',
    'lb-client-name': 'Client name',
    'lb-contact-information': 'Contact information',
    'lb-phone-number': 'Customers telephone',
    'lb-localization': 'Location',
    'lb-state': 'State',
    'lb-select-state': 'Select a state',
    'lb-simulation-information': 'Simulation information',
    'btn-choose-vehicle': 'Choose vehicle',
    'lb-brands': 'Brands',
    'lb-simulate': 'Simulate',
    'lb-model': 'Fashion model',
    'lb-national': 'National',
    'lb-imported': 'Imported',
    'lb-create-by': 'Created by',
    'lb-creation-date': 'Creation date',
    'lb-financial-brands': 'Financial brands',
    'lb-publish': 'Publish',
    'btn-save-news': 'Save news',
    'lb-list-of-registered-news': 'List of registered news',
    'lb-new-title': 'News title',
    'lb-actions': 'Actions',
    'lb-commission-level': 'Release of return',
    'lb-vendor-manager': 'Salesman / manager',
    'lb-select-a': 'Select one',
    'lb-product': 'Product',
    'lb-select-return': 'Select return',
    'lb-release': 'Release',
    'btn-release': 'Release',
    'lb-release-date': 'Release date',
    'lb-fleet-code': 'Fleet code',
    'lb-commission-level-date': 'Release date',
    'lb-release-by': 'Liberator by',
    'lb-released-level': 'Return released',
    'lb-validate': 'Shelf life',
    'lb-proposal': 'Proposal',
    'lb-salesman': 'Salesman',
    'lb-dealer-proposal': 'Concession dealer proposals',
    'lb-client': 'Client',
    'lb-status': ' status',
    'lb-financed': 'Funded',
    'lb-table': 'Table',
    'lk-reassign': 'To repay',
    'lb-detailing': 'Detailing',
    'lb-reassign': 'To repay',
    'btn-reassign': 'Reassign',
    'lb-amount-financed': 'Amount financed',
    'lb-validate-date': 'Expiration date',
    'lb-previous-concessionaire': 'Previous concessionaire',
    'lb-new-concessionaire': 'New dealer',
    'lb-the-proposal-number': 'The proposal number',
    'lb-name': 'Name',
    'lb-simulation-print': 'Print out',
    'btn-simulation-print': 'Print out',
    'text-warning-conjugue': 'You have selected the "spouse / companion" paradox degree so that the client spouse\'s data will be copied to the accurate 1 data and any changes will be replicated between the two screens. Do you confirm the relationship level?',
    'lb-model-selected': 'Selected model',
    'lb-vehicle-value': 'Value of the vehicle',
    'lb-optional': 'Optional',
    'lb-accessories': 'Accessories',
    'lb-accessorie': 'Accessory',
    'lb-value': 'Value',
    'lb-subtotal-options': 'Subtotal of options',
    'lb-subtotal-accessories': 'Subtotal accessories',
    'lb-total': 'Total',
    'lb-vehicle': 'Vehicle',
    'lb-manufacturing-year': 'Year of manufacture',
    'lb-model-year': 'Model year',
    'lb-vehicle-type': 'Type of vehicle',
    'lb-value-car': 'Car value',
    'lb-total-value': 'Amount',
    'lb-review-connected-simulation': 'Review checked simulation',
    'lb-financial-type': 'Type of financing',
    'lb-lack': 'Lack',
    'lb-entrance': 'Input',
    'lb-financial-during': 'Duration of funding',
    'lb-contracted-services': 'Contracted services',
    'lb-financial-protection-insurance': 'Financial protection insurance',
    'lb-safe-tranquility': 'Safe tranquility',
    'lb-safe-auto': 'Auto insurance',
    'lb-monthly': 'Monthly',
    'lb-total-financial': 'Total financing',
    'lb-edit-vehicle': 'Edit vehicle',
    'lb-custumer-card': 'Customer form',
    'lb-installments': 'Plots',
    'lb-payment-plan': 'Payment plan',
    'lb-call-condition': 'Call condition',
    'lb-services': 'Services',
    'lb-and': 'And',
    'lb-insurance': 'Insurance',
    'lb-see-services-and-insurance': 'View services and insurance',
    'lb-total-funded': 'Total funded',
    'lb-custumer-rate': 'Customer rate',
    'lb-contract': 'To hire',
    'lb-simulation': 'Simulation',
    'lb-add-new': 'Add new',
    'btn-see-services-and-insurance': 'View services and insurance',
    'lb-insert-optionals-and-accessories': 'Insert options and accessories',
    'lb-custumer-data': 'Client\'s data',
    'btn-edit-information': 'Edit information',
    'lb-residential-data': 'Residential data',
    'lb-spouse': 'Spouse',
    'lb-professional-data': 'Professional data',
    'lb-personal-references': 'Personal references',
    'lb-bank-data': ' bank data',
    'lb-custumer-edit': 'Edit client',
    'lb-proposal-history': 'Proposal history',
    'lb-comercial-phone-number': 'Commercial phone',
    'msg-invalid-cpf-cnpj': 'Invalid cpf / cnpj field',
    'msg-invalid-email': 'Invalid email field',
    'lb-number': 'Number',
    'lb-address': 'Address',
    'lb-complement': 'Complement',
    'lb-neighborhood': 'Neighborhood',
    'lb-city': 'City',
    'lb-citizenship': 'Citizenship',
    'lb-naturalness': 'Naturalness',
    'lb-type-of-residence': 'Type of residence',
    'lb-lives-in-address-since': 'Lives at address from',
    'lb-mailing-address': 'Mailing address',
    'lb-bank': 'Bank',
    'lb-code-bank': 'Bank code',
    'lb-agency': 'Agency',
    'lb-checking-account': 'Current account',
    'lb-custumer-since': 'Customer since',
    'lb-type-account': 'Account type',
    'lb-phone-agency': 'Agency telephones',
    'btn-vehicle-data': 'Vehicle data',
    'lb-gender': 'Sex',
    'lb-date-of-birth': 'Date of birth',
    'lb-marital-status': 'Marital status',
    'lb-residencial-number': 'Home phone',
    'lb-phone-type': 'Phone type',
    'lb-cel-phone': 'Cell phone',
    'lb-nationality': 'Nationality',
    'lb-person-politically-exposed': 'Political person',
    'lb-education-degree': 'Degree of institution',
    'lb-physical-deficiency': 'Physical deficiency',
    'lb-name-of-the-father': 'Name of the father',
    'lb-name-of-the-mother': 'Mother\'s name',
    'lb-document-type': 'Document type',
    'lb-document-number': 'Document number',
    'lb-document-country': 'Country of document',
    'lb-uf-document': 'Uf of the document',
    'lb-emission-date': 'Date of issue',
    'lb-issuing-board': 'Issuing body',
    'lb-company-name': 'Company name',
    'lb-legal-nature': 'Legal nature',
    'lb-telephone': 'Phone',
    'lb-telephone-extension': 'Branch',
    'lb-open-date': 'Open date',
    'lb-company-size': 'Company size',
    'lb-head-office': 'Own headquarters',
    'lb-monthly-billing': 'Monthly invoicing',
    'lb-groups-activity-economic': 'Economic activity groups',
    'lb-activity-economic': 'Economic activity',
    'btn-residential-data': 'Residential data',
    'lb-lives-in-address-from': 'Lives at address from',
    'btn-personal-references': 'Personal references',
    'lb-full-name': 'Full name',
    'btn-banking-reference': 'Bank reference',
    'lb-occupation': 'Occupation',
    'lb-role': 'Function',
    'lb-office': 'Office',
    'lb-comercial-phone': 'Commercial phone',
    'lb-size-company': 'Porte',
    'lb-admission-date': 'Admission date',
    'lb-patrimony': 'Patrimony',
    'lb-type-of-income': 'Type of income',
    'lb-type-of-income-report': 'Type of proof of income',
    'lb-monthly-income': 'Monthly income',
    'lb-others-icome': 'Other income',
    'lb-cellphone': 'Cell phone',
    'lb-agency-phone-number': 'Agency Phone',
    'btn-professional-data': 'Professional data',
    'lb-chassis-number': 'Chassis number',
    'lb-register-number': 'Register number',
    'lb-registration-province': 'Registration status',
    'lb-licensing-province': 'Licensing status',
    'lb-color': 'Color',
    'lb-origin': 'Source',
    'btn-guarantor': 'Guarantor',
    'lb-vehicle-data': 'Vehicle data',
    'lb-credit-report': 'Credit report',
    'lb-actor': 'Actor',
    'lb-date': 'Date',
    'lbl-vehicle': 'Vehicle',
    'lbl-input-value': 'Input value',
    'lbl-plot-amount': 'Plot amount',
    'lbl-customer-contacts': 'Customer contacts',
    'lbl-email': 'Email',
    'btn-return-shipping': 'Back to shipping',
    'btn-available-documentation': 'Available documentation',
    'lb-description': 'Description',
    'btn-print': 'Print out',
    'btn-back-to-custumer-card': 'Back to client card',
    'lb-choose-brand-new-one': 'Choose a brand new',
    'lb-choose-model': 'Choose a template',
    'lb-choose-version': 'Choose version',
    'lb-choose-model-year': 'Choose the model year',
    'lb-price-base': 'Base price',
    'lb-direct-sale': 'Direct selling',
    'lb-show-room': 'Show room',
    'lb-new-ones': 'New',
    'lb-sale-type': 'Type of sale',
    'btn-simulation': 'Simulation',
    'lb-select-profile': 'Select a profile',
    'lb-dealership-code': 'Dealer code',
    'lb-close': 'Close',
    'lb-dont-exempt-registration-fee': 'Do not exempt registration fee',
    'lb-exempt-customer-registration-fee': 'Exempt customer registration fee',
    'lb-send': 'Send',
    'lb-yes': 'Yes',
    'lb-no': 'No',
    'lb-submission-process-configuration': 'Setting up the submission process',
    'lb-select-type-change': 'Select a type of change',
    'lb-authorized': 'Authorized',
    'lb-not-authorized': 'Not authorized',
    'msg-sucesso-save': 'Saved successfully.',
    'lb-required-field': 'Required field',
    'simulation-windows': 'Simulation windows',
    'windows': 'Windows',
    'language': 'Language',
    'change-password2': 'Change password',
    'logout2': 'Get out',
    'msg_invalid_login': 'Incorrect user or password',
    'msg_inative_user': 'Inactive user. Contact dealer administrator',
    'msg_login_success': 'Login successfully completed',
    'msg-invalid-token': 'Invalid token. Request a new password change',
    'msg-invalid-user-email': 'User / e-mail does not match the registered user in the database',
    'msg-new-passwords-doesnt-check': 'New password and new password confirmation do not match',
    'msg-password-validation': 'The new password must have at least one numeric character. At least one alphanumeric character',
    'msg-send-mail-success': 'Email successfully sent',
    'msg-new-password-must-be-equal': 'New passwords must be the same',
    'msg-new-password-must-be-different-old-one': 'New password must be different from current password',
    'msg-current-password-incorrect': 'Incorrect current password',
    'msg-change-password-success': 'Password changed successfully',
    'No-dealerships-to-profile': 'No dealers for the indicated filter',
    'no-salesman-to-dealership': 'There are no vendors for the selected dealership.',
    'lb-change-date': 'Date of change',
    'lb-proposal-adp-number': 'Adp proposal no.',
    'lb-read': 'Read',
    'lbl-aviso': 'Confirmation of link between client and guarantor?',
    'lb-contract-selected-services': 'Hire selected services',
    'msg-bad-request-service-santander': 'Service temporarily unavailable please try again in a few seconds.',
    'msg-bad-request-service-s3': 'Service temporarily unavailable please try again in a few seconds.',
    'msg-doc-generated': 'Document generated successfully.',
    'msg-error-send-email': 'Error sending email.',
    'msg-error-generated-doc': 'Error in preparing the documentation.',
    'common-msg-maintenance': 'Maintenance functionality',
    'common-msg-unavailable': 'Not currently available',
    'msg-worn-session-expired-401': 'Session expired.',
    'lb-repackage': 'Package',
    'lb-delay': 'Lack',
    'lb-entrance-value': 'Input Value',
    'lb-entrance-percent': '% input',
    'lb-contracted': 'Contracted',
    'lb-contracted-sub': 'Click to proceed',
    'lb-residential-data_guarantor_1': 'Resident Data Guarantor 1',
    'lb-residential-data_guarantor_2': 'Residence Data Guarantor 2',
    'msg-send-santander-confirmation': 'Do you want to submit this proposal for credit analysis?',
    'lb-uf': 'UF',
    'lb-branch': 'Agency',
    'lb-digit': 'Digit',
    'lb-account': 'Checking Account',
    'lb-phone-branch': 'Agency Phone',
    'lb-of-document': 'of the Document',
    'lb-country': 'Parents',
    'no-delaerships-to-profile': 'No dealers for the indicated filter',
    'btn-vehicle': 'Vehicle',
    'lb-edit-simulation': 'Edit Simulation',
    'lb-edit-customer-card': 'Edit Customer Sheet',
    'lb-resum': 'summary',
    'btn-fill-customer-card': 'Fill in the Customer Form',
    'lb-review-contracted-simulation': 'Review Contracted Simulation',
    'lb-compare': 'To compare',
    'lb-months': 'months',
    'lb-days': 'days',
    'lb-name-certified-agent': 'Certified agent name',
    'lb-certified-number': 'Certificate number',
    'lb-certified-valid-date': 'Date validity certificate',
    'btn-validate-proposal': 'Validate Proposal',
    'lb-submission': 'Submission',
    'btn-customer-data': 'Client\'s data',
    'btn-contract-service': 'Contract Services',
    'lb-guarantor-data': 'Details of the guarantor',
    'lb-guarantor': 'Guarantor',
    'lb-banking-references': 'Banking references',
    'lb-back-to-customer-card': 'Back to Customer Form',
    'lb-back-to-send': 'Back to Shipping',
    'tab-utility-car': 'Tools',
    'tab-car': 'Car',
    'lb-edit-customer': 'Edit Client',
    'lb-customer-data': 'Client\'s data',
    'btn-send-proposal': 'Submit Proposal',
    'lb-select-guarantor-type': 'Select a type of Guarantor',
    'lb-type-of-relationship-company': 'Type of relationship',
    'lb-degree-of-kinship': 'Degree of kinship',
    'lb-guarantor-type': 'Type of Guarantor',
    'btn-spouse': 'Spouse',
    'btn-auto-insurance': 'Seguro auto'
};
//# sourceMappingURL=lang-en.js.map