"use strict";
// lang-es.ts
Object.defineProperty(exports, "__esModule", { value: true });
exports.LANG_ES_NAME = 'es';
exports.LANG_ES_TRANS = {
    'PF': 'Persona física',
    'PJ': 'Persona jurídica',
    'true': 'Sí',
    'false': 'No',
    'common-msg-success-header': 'Éxito',
    'common-msg-info-header': 'Información',
    'common-msg-warn-header': 'Advertencia',
    'common-msg-error-header': 'Error',
    'common-msg-success': 'Ejecución ok',
    'common-msg-info': 'Acceso denegado',
    'common-msg-warn': 'Error de negociación',
    'common-msg-error': 'Error interno',
    'common-msg-403': 'Acceso denegado',
    'login_lb_title': 'Inicio de sesión',
    'login-lb-user': 'Usuario',
    'login-lb-password': 'Contraseña',
    'msg-error-login': 'Debe rellenar el campo de usuario',
    'msg-error-password': 'Debe rellenar el campo de contraseña',
    'btn-new-simulation': 'Nueva simulación',
    'btn-my-proposals': 'Mis propuestas',
    'btn-login': 'Inicio',
    'btn-my-profile': 'Perfil',
    'btn-administration': 'Administración',
    'btn-insurance': 'Seguros',
    'lb-change-password': 'Cambio de contraseña',
    'lb-password-field-required-size': '¡campo obligatorio! (mínimo 6 caracteres)',
    'lb-current-password': 'Contraseña actual',
    'lb-new-password': 'Nueva contraseña',
    'lb-confirm-password': 'Confirmación de contraseña',
    'btn-notifications': 'Notificaciones',
    'lb-notifications': 'Notificaciones',
    'btn-change-brand': 'Intercambiar marca',
    'lb-all-notification': 'Ver todas las notificaciones',
    'msg-not-connected': 'No conectado',
    'btn-edit': 'Edición',
    'btn-save': 'Guardar',
    'btn-clear': 'Limpiar',
    'btn-delete': 'Excluir',
    'btn-continue': 'Continuar',
    'lb-password-field-required': 'Campo no rellenado.',
    'lk-forgot-password': 'Olvide mi contraseña',
    'lb-forgot-password': 'Olvide mi contraseña',
    'forgot-password-lb-useremail': 'Usuario / e-mail',
    'forgot-password-msg': 'Informe a su usuario o dirección de correo electrónico para recibir un correo electrónico con el vínculo para crear la nueva contraseña',
    'lb-news': 'Noticias',
    'lb-support': 'Soporte técnico',
    'lb-help-desk': 'Para reporte de problemas o dudas entre en contacto con el help desk del sistema.',
    'lb-phone-help-desk': 'Teléfono help desk',
    'lb-email-support': 'E-mail del soporte',
    'btn-deactivation-of-services': 'Desactivación de servicios',
    'btn-services-configuration': 'Configuración de servicios',
    'btn-services-configuration-required': 'Configuración de servicios obligatorios',
    'btn-dealer-proposal': 'Propuestas con cambio de concesionaria',
    'btn-required': 'Obligatorio',
    'btn-commission-level': 'Liberación de retorno',
    'btn-submission-process-configuration': 'Configuración del proceso de envío',
    'btn-proposal-update': 'Actualización de propuestas',
    'btn-news-administration': 'Administración de noticias',
    'btn-promotional-images': 'Imágenes promocionales',
    'lb-promotional-images': 'Imágenes promocionales',
    'btn-models': 'Modelos',
    'msg-image-size': 'La imagen debe tener las dimensiones mínimas de 1024x435 px y un tamaño máximo de 8mb.',
    'lb-select-brand': 'Seleccione la marca',
    'msg-error-extension': 'Sólo se permiten archivos con las siguientes extensiones',
    'msg-error-max-size': 'La imagen debe tener un tamaño máximo de 8mb.',
    'msg-sucesso-save-image': 'La imagen guardada con éxito.',
    'msg-sucesso-remove-image': 'Imagen eliminada con éxito.',
    'msg-info-select-financi-brand': 'Usted debe seleccionar una Marca Financeira.',
    'lb-avaliable-services': 'Servicios disponibles',
    'lb-avaliable-service': 'Servicio disponible',
    'lb-service-unavaliable': 'Servicio no disponible',
    'lb-dealerships': 'Concesionarios',
    'lb-avaliable': 'Disponible',
    'lb-not-avaliable': 'No disponible',
    'lb-mandatory-services': 'Servicios obligatorios',
    'lb-required': 'Obligatorio',
    'lb-not-required': 'No obligatorio',
    'lb-check-with-RCI-comercial-consultant': 'Comprobar con el consultor comercial rci',
    'lb-brand': 'Marca',
    'btn-choose-file': 'Elegir archivo',
    'btn-remove': 'Eliminar',
    'lb-vehicle-band': 'Marca del vehículo',
    'lb-vehicle-model': 'Modelo del vehículo',
    'lb-vehicle-version': 'Versión del vehículo',
    'lb-version': 'Versión',
    'msg-image-size-modelo': 'Imagen con un tamaño superior al permitido. \ n seleccione un archivo de más de 2 mb',
    'msg-images-registered-brand': 'No hay imágenes registradas para la marca',
    'msg-images-registered-model': 'No hay imágenes registradas para el modelo',
    'msg-images-registered-version': 'No hay imágenes registradas para la versión',
    'update-button-behavior-configuration': 'Configuración de comportamiento del botón actualizar',
    'lb-welcome': 'Bienvenido',
    'lb-connected-by': 'Conectado como',
    'lb-back-your-profile': 'Volver a su perfil',
    'btn-search': 'Búsqueda',
    'btn-reset': 'Resto del día',
    'btn-enter': 'Entrar',
    'lb-proposal-number': 'Número de la propuesta',
    'lb-customer-type': 'Tipo cliente',
    'btn-logout': 'Salir',
    'btn-send': 'Enviar enviar',
    'lb-my-agreements': 'Mis propuestas',
    'lb-client-type': 'Tipo cliente',
    'lb-status-proposal': 'Estado de la propuesta',
    'lb-date-initial-creation': 'Fecha de creación inicial',
    'lb-date-final-creation': 'Fecha creación final',
    'lb-date-initial-validate': 'Fecha de vencimiento inicial',
    'lb-date-final-validate': 'Fecha de vencimiento',
    'lb-dealership': 'Concesionaria',
    'lb-exemption': 'Exención',
    'lb-with': 'Con el fin',
    'lb-of': 'En este sentido,',
    'lb-custumer-personal-data': 'Datos personales del cliente',
    'lb-cpf-cnpj': 'Cpf o cnpj',
    'lb-client-name': 'Nombre del cliente',
    'lb-contact-information': 'Datos de contacto',
    'lb-phone-number': 'Teléfono del cliente',
    'lb-localization': 'Ubicación',
    'lb-state': 'Estado',
    'lb-select-state': 'Seleccione un estado',
    'lb-simulation-information': 'Información de simulación',
    'btn-choose-vehicle': 'Elegir vehículo',
    'lb-brands': 'Marcas',
    'lb-simulate': 'Simular',
    'lb-model': 'Modelo',
    'lb-national': 'Nacional',
    'lb-imported': 'Importada.',
    'lb-create-by': 'Criado por',
    'lb-creation-date': 'Fecha de creación',
    'lb-financial-brands': 'Marcas financieras',
    'lb-publish': 'Publicar',
    'btn-save-news': 'Noticias',
    'lb-list-of-registered-news': 'Lista de noticias registradas',
    'lb-new-title': 'Título de la noticia',
    'lb-actions': 'Acciones',
    'lb-commission-level': 'Liberación de retorno',
    'lb-vendor-manager': 'Vendedor / gerente',
    'lb-select-a': 'Seleccione uno',
    'lb-product': 'Producto',
    'lb-select-return': 'Seleccione retorno',
    'lb-release': 'Liberar',
    'btn-release': 'Liberar',
    'lb-release-date': 'Fecha de liberación',
    'lb-fleet-code': 'Código frota',
    'lb-commission-level-date': 'Fecha de publicación',
    'lb-release-by': 'Liberador por',
    'lb-released-level': 'Retorno liberado',
    'lb-validate': 'Validez',
    'lb-proposal': 'Propuesta',
    'lb-salesman': 'Vendedor',
    'lb-dealer-proposal': 'Propuestas con cambio de concesionaria',
    'lb-client': 'Cliente',
    'lb-status': ' estado',
    'lb-financed': 'Financiado',
    'lb-table': 'Tabla',
    'lk-reassign': 'Retribuir',
    'lb-detailing': 'Detalle',
    'lb-reassign': 'Retribuir',
    'btn-reassign': 'Reasignar',
    'lb-amount-financed': 'Importe financiado',
    'lb-validate-date': 'Fecha de vencimiento',
    'lb-previous-concessionaire': 'Concesionaria anterior',
    'lb-new-concessionaire': 'Nueva concesionaria',
    'lb-the-proposal-number': 'La propuesta número',
    'lb-name': 'Nombre',
    'lb-simulation-print': 'Imprimir imprimir',
    'btn-simulation-print': 'Imprimir imprimir',
    'text-warning-conjugue': 'Usted seleccionó el grado de parantesco "conjuge / compañero" con eso los datos del cónyuge del cliente serán copiados a los datos del avalista 1 y cualquier alteración será replicada entre las dos pantallas. ¿confirmas el grado de parentesco?',
    'lb-model-selected': 'Modelo seleccionado',
    'lb-vehicle-value': 'Valor del vehículo',
    'lb-optional': 'Opcionales',
    'lb-accessories': 'Accesorios',
    'lb-accessorie': 'Accesorio',
    'lb-value': 'Valoraciones',
    'lb-subtotal-options': 'Subtotal de opciones',
    'lb-subtotal-accessories': 'Subtotal accesorios',
    'lb-total': 'Total',
    'lb-vehicle': 'Vehículo',
    'lb-manufacturing-year': 'Año de fabricación',
    'lb-model-year': 'Año del modelo',
    'lb-vehicle-type': 'Tipo de vehículo',
    'lb-value-car': 'Valor del coche',
    'lb-total-value': 'Valor total',
    'lb-review-connected-simulation': 'Revisar la simulación constatada',
    'lb-financial-type': 'Tipo de financiación',
    'lb-lack': 'Carencia',
    'lb-entrance': 'Entrada',
    'lb-financial-during': 'Duración de la financiación',
    'lb-contracted-services': 'Servicios contratados',
    'lb-financial-protection-insurance': 'Seguro de protección financiera',
    'lb-safe-tranquility': 'Seguro de tranquilidad',
    'lb-safe-auto': 'Seguro auto',
    'lb-monthly': 'Mensual',
    'lb-total-financial': 'Financiación total',
    'lb-edit-vehicle': 'Editar vehículo',
    'lb-custumer-card': 'Ficha del cliente',
    'lb-installments': 'Parcelas',
    'lb-payment-plan': 'Plan de pago',
    'lb-call-condition': 'Condición de llamada',
    'lb-services': 'Servicios',
    'lb-and': 'Y de las personas',
    'lb-insurance': 'Seguros',
    'lb-see-services-and-insurance': 'Ver servicios y seguros',
    'lb-total-funded': 'Total financiado',
    'lb-custumer-rate': 'Tasa de cliente',
    'lb-contract': 'Contratación',
    'lb-simulation': 'Simulación',
    'lb-add-new': 'Añadir nueva foto',
    'btn-see-services-and-insurance': 'Ver servicios y seguros',
    'lb-insert-optionals-and-accessories': 'Insertar opciones y accesorios',
    'lb-custumer-data': 'Datos del cliente',
    'btn-edit-information': 'Editar información',
    'lb-residential-data': 'Datos residenciales',
    'lb-spouse': 'Cónjugue',
    'lb-professional-data': 'Datos profesionales',
    'lb-personal-references': 'Referencias personales',
    'lb-bank-data': ' datos bancarios',
    'lb-custumer-edit': 'Editar cliente',
    'lb-proposal-history': 'Historia de la propuesta',
    'lb-comercial-phone-number': 'Teléfono Comercial',
    'msg-invalid-cpf-cnpj': 'Campo cpf / cnpj no válido',
    'msg-invalid-email': 'E-mail no válido',
    'lb-number': 'Número',
    'lb-address': 'Dirección',
    'lb-complement': 'Complemento',
    'lb-neighborhood': 'Barrio',
    'lb-city': 'Ciudad',
    'lb-citizenship': 'Ciudadanía',
    'lb-naturalness': 'Nacimiento',
    'lb-type-of-residence': 'Tipo de residencia',
    'lb-lives-in-address-since': 'Reside en la dirección desde',
    'lb-mailing-address': 'Dirección de correspondencia',
    'lb-bank': 'Banco',
    'lb-code-bank': 'Codigo banco',
    'lb-agency': 'Agencia',
    'lb-checking-account': 'Cuenta corriente',
    'lb-custumer-since': 'Cliente desde',
    'lb-type-account': 'Tipo de cuenta',
    'lb-phone-agency': 'Telelefono de la agencia',
    'btn-vehicle-data': 'Datos del vehículo',
    'lb-gender': 'Sexo',
    'lb-date-of-birth': 'Fecha de nacimiento',
    'lb-marital-status': 'Estado civil',
    'lb-residencial-number': 'Teléfono residencial',
    'lb-phone-type': 'Tipo de teléfono',
    'lb-cel-phone': 'Teléfono celular',
    'lb-nationality': 'Nacionalidad',
    'lb-person-politically-exposed': 'Persona políticamente expuesta',
    'lb-education-degree': 'Grado de institución',
    'lb-physical-deficiency': 'Deficiencia física',
    'lb-name-of-the-father': 'Nombre del padre',
    'lb-name-of-the-mother': 'Nombre de la madre',
    'lb-document-type': 'Tipo de documento',
    'lb-document-number': 'Número de documento',
    'lb-document-country': 'País del documento',
    'lb-uf-document': 'Uf del documento',
    'lb-emission-date': 'Fecha de emisión',
    'lb-issuing-board': 'Órgano emisor',
    'lb-company-name': 'Nombre de la empresa',
    'lb-legal-nature': 'Jurisprudencia',
    'lb-telephone': 'Teléfono',
    'lb-telephone-extension': 'Extensión',
    'lb-open-date': 'Fecha de apertura',
    'lb-company-size': 'Tamaño de la empresa',
    'lb-head-office': 'Sede propia',
    'lb-monthly-billing': 'Facturación mensual',
    'lb-groups-activity-economic': 'Grupos actividad económica',
    'lb-activity-economic': 'Actividad económica',
    'btn-residential-data': 'Datos residenciales',
    'lb-lives-in-address-from': 'Reside en la dirección desde',
    'btn-personal-references': 'Referencias personales',
    'lb-full-name': 'Nombre completo',
    'btn-banking-reference': 'Referencia bancaria',
    'lb-occupation': 'Ocupación',
    'lb-role': 'Función',
    'lb-office': 'Cargo',
    'lb-comercial-phone': 'Teléfono comercial',
    'lb-size-company': 'Porteño',
    'lb-admission-date': 'Fecha de admisión',
    'lb-patrimony': 'Patrimonio',
    'lb-type-of-income': 'Tipo de renta',
    'lb-type-of-income-report': 'Tipo de comprobación de ingresos',
    'lb-monthly-income': 'Renta mensual',
    'lb-others-icome': 'Otras renta',
    'lb-cellphone': 'Teléfono celular',
    'lb-agency-phone-number': 'Teléfono de la Agencia',
    'btn-professional-data': 'Datos profesionales',
    'lb-chassis-number': 'Número de chasis',
    'lb-register-number': 'Número de registro',
    'lb-registration-province': 'Estado de registro',
    'lb-licensing-province': 'Estado de licencias',
    'lb-color': 'Color',
    'lb-origin': 'Origen',
    'btn-guarantor': 'Evaluador',
    'lb-vehicle-data': 'Datos del vehículo',
    'lb-credit-report': 'Dictamen de crédito',
    'lb-actor': 'Actor',
    'lb-date': 'Fecha',
    'lbl-vehicle': 'Vehículo',
    'lbl-input-value': 'Valor de entrada',
    'lbl-plot-amount': 'Valor de la parcela',
    'lbl-customer-contacts': 'Contactos del cliente',
    'lbl-email': 'E-mail',
    'btn-return-shipping': 'Volver a la lista',
    'btn-available-documentation': 'Documentación disponible',
    'lb-description': 'Descripción',
    'btn-print': 'Imprimir imprimir',
    'btn-back-to-custumer-card': 'Volver a la ficha del cliente',
    'lb-choose-brand-new-one': 'Seleccione la marca de un seminuevo',
    'lb-choose-model': 'Seleccione un modelo',
    'lb-choose-version': 'Seleccione la versión',
    'lb-choose-model-year': 'Seleccione el año de modelo',
    'lb-price-base': 'Precio base',
    'lb-direct-sale': 'Venta directa',
    'lb-show-room': 'Room service',
    'lb-new-ones': 'Semillas',
    'lb-sale-type': 'Tipo de venta',
    'btn-simulation': 'Simulación',
    'lb-select-profile': 'Seleccione un perfil',
    'lb-dealership-code': 'Código de la concesionaria',
    'lb-close': 'Cerrar cerrar',
    'lb-dont-exempt-registration-fee': 'No eximir la tasa de registro',
    'lb-exempt-customer-registration-fee': 'Eximir la tasa de registro del cliente',
    'lb-send': 'Envío',
    'lb-yes': 'Sí',
    'lb-no': 'No es posible',
    'lb-submission-process-configuration': 'Configuración del proceso de envío',
    'lb-select-type-change': 'Seleccione un tipo de cambio',
    'lb-authorized': 'Autorizado',
    'lb-not-authorized': 'No autorizado',
    'msg-sucesso-save': 'Salvo con éxito.',
    'lb-required-field': 'Campo obligatorio',
    'simulation-windows': 'Ventas de simulación',
    'windows': 'Ventanas',
    'language': 'Idioma',
    'change-password2': 'Cambiar contraseña',
    'logout2': 'Salir',
    'msg_invalid_login': 'Usuario o contraseña incorrecta',
    'msg_inative_user': 'Usuario inactivo. Póngase en contacto con el administrador de concesionarios',
    'msg_login_success': 'Iniciar sesión con éxito',
    'msg-invalid-token': 'Token no válido. Solicite nuevo cambio de contraseña',
    'msg-invalid-user-email': 'Usuario / e-mail no confiere con el registro en la base de datos',
    'msg-new-passwords-doesnt-check': 'Nueva contraseña y confirmación de nueva contraseña no confieren',
    'msg-password-validation': 'La nueva contraseña debe tener al menos un carácter numérico. Al menos un carácter alfanumérico,',
    'msg-send-mail-success': 'Correo electrónico enviado con éxito',
    'msg-new-password-must-be-equal': 'Las nuevas contraseñas deben ser iguales',
    'msg-new-password-must-be-different-old-one': 'La nueva contraseña debe ser diferente de la contraseña actual',
    'msg-current-password-incorrect': 'Contraseña actual incorrecta',
    'msg-change-password-success': 'Contraseña alterada con éxito',
    'No-dealerships-to-profile': 'Sin concesionarios para el filtro indicado',
    'no-salesman-to-dealership': 'No hay vendedores para la concesionaria seleccionada',
    'lb-change-date': 'Fecha de modificación',
    'lb-proposal-adp-number': 'Propuesta adp n °',
    'lb-read': 'Leído',
    'lbl-aviso': 'Confirmación de vínculo entre cliente y avalista?',
    'lb-contract-selected-services': 'Contratar servicios seleccionados',
    'msg-bad-request-service-santander': 'El servicio temporalmente no intenta volver a intentar en unos segundos.',
    'msg-bad-request-service-s3': 'El servicio temporalmente no intenta volver a intentar en unos segundos.',
    'msg-doc-generated': 'Documento generado con éxito.',
    'msg-error-send-email': 'Error al enviar correo electrónico.',
    'msg-error-generated-doc': 'Error al elaborar la documentación.',
    'common-msg-maintenance': 'Funcionalidad en mantenimiento',
    'common-msg-unavailable': 'No disponible en este momento',
    'msg-worn-session-expired-401': 'Sesión caducada.',
    'lb-repackage': 'Paquete',
    'lb-delay': 'Carencia',
    'lb-entrance-value': 'Valor de entrada',
    'lb-entrance-percent': '% de entrada',
    'lb-contracted': 'Contratación',
    'lb-contracted-sub': 'Haga clic para avanzar',
    'lb-residential-data_guarantor_1': 'Datos residenciales Evaluadora 1',
    'lb-residential-data_guarantor_2': 'Datos residenciales Evaluadora 2',
    'msg-send-santander-confirmation': '¿Desea enviar esta propuesta para el análisis de crédito?',
    'lb-uf': 'UF',
    'lb-branch': 'Agencia',
    'lb-digit': 'Dígito',
    'lb-account': 'Cuenta corriente',
    'lb-phone-branch': 'Teléfono de la agencia',
    'lb-of-document': 'del documento',
    'lb-country': 'Los padres',
    'no-delaerships-to-profile': 'Sin concesionarios para el filtro indicado',
    'btn-vehicle': 'Vehículo',
    'lb-edit-simulation': 'Editar Simulación',
    'lb-edit-customer-card': 'Editar ficha del cliente',
    'lb-resum': 'Resumen',
    'btn-fill-customer-card': 'Relleno del cliente',
    'lb-review-contracted-simulation': 'Revisión de la simulación contratada',
    'lb-compare': 'Comparar precios',
    'lb-months': 'meses',
    'lb-days': 'días',
    'lb-name-certified-agent': 'Nombre de agente certificado',
    'lb-certified-number': 'Número de certificado',
    'lb-certified-valid-date': 'Fecha de vencimiento certificado',
    'btn-validate-proposal': 'Validar Propuesta',
    'lb-submission': 'Submisión',
    'btn-customer-data': 'Datos del cliente',
    'btn-contract-service': 'Contratar Servicios',
    'lb-guarantor-data': 'Datos del avalista',
    'lb-guarantor': 'Evaluador',
    'lb-banking-references': 'Referencias Bancarias',
    'lb-back-to-customer-card': 'Volver a la ficha del cliente',
    'lb-back-to-send': 'Volver al envío',
    'tab-utility-car': 'Utilidades',
    'tab-car': 'Coche',
    'lb-edit-customer': 'Editar cliente',
    'lb-customer-data': 'Datos del cliente',
    'btn-send-proposal': 'Enviar propuesta',
    'lb-select-guarantor-type': 'Seleccione un tipo de Avalista',
    'lb-type-of-relationship-company': 'Tipo de relación empresa',
    'lb-degree-of-kinship': 'Grado de parentezco',
    'lb-guarantor-type': 'Tipo de Avalista',
    'btn-spouse': 'Cónyuge',
};
//# sourceMappingURL=lang-es.js.map