// lang-fr.ts

export const LANG_FR_NAME = 'fr';

export const LANG_FR_TRANS = {
    'PF':'Les personnes',
    'PJ':'Entité juridique',
    'true':'Oui.',
    'false':'Non.',
    'common-msg-success-header':'Succès',
    'common-msg-info-header':'Information',
    'common-msg-warn-header':'Avertissement',
    'common-msg-error-header':'Erreur',
    'common-msg-success':'Exécution ok',
    'common-msg-info':'Accès refusé',
    'common-msg-warn':'Erreur de négociation',
    'common-msg-error':'Erreur interne',
    'common-msg-403':'Accès refusé',
    'login_lb_title':'Connexion titre',
    'login-lb-user':'Utilisateur',
    'login-lb-password':'Mot de passe',
    'msg-error-login':'Vous devez remplir le champ utilisateur',
    'msg-error-password':'Vous devez remplir le champ de mot de passe',
    'btn-new-simulation':'Nouvelle simulation',
    'btn-my-proposals':'Mes propositions',
    'btn-login':'Login',
    'btn-my-profile':'Profil',
    'btn-administration':'Administration',
    'btn-insurance':'Assurance',
    'lb-change-password':'Changement de mot de passe',
    'lb-password-field-required-size':'Champ obligatoire! (6 caractères minimum)',
    'lb-current-password':'Mot de passe actuel',
    'lb-new-password':'Nouveau mot de passe',
    'lb-confirm-password':'Confirmation mot de passe',
    'btn-notifications':'Notifications',
    'lb-notifications':'Notifications',
    'btn-change-brand':'Marque changement',
    'lb-all-notification':'Voir toutes les notifications',
    'msg-not-connected':'Non connecté',
    'btn-edit':'Editer',
    'btn-save':'Sauver',
    'btn-clear':'Propre',
    'btn-delete':'Effacer',
    'btn-continue':'Continuer',
    'lb-password-field-required':'Le champs ne rempli.',
    'lk-forgot-password':'J\'ai oublié mon mot de passe',
    'lb-forgot-password':'J\'ai oublié mon mot de passe',
    'forgot-password-lb-useremail':'Utilisateur / email',
    'forgot-password-msg':'Entrez votre nom d\'utilisateur ou adresse e-mail pour recevoir un email avec le lien pour créer un nouveau mot de passe',
    'lb-news':'Nouvelles',
    'lb-support':'Titulaire',
    'lb-help-desk':'Pour des problèmes ou des questions signaler s\'il vous plaît contacter le système de help desk.',
    'lb-phone-help-desk':'Téléphone help desk',
    'lb-email-support':'Support e-mail',
    'btn-deactivation-of-services':'Annulation de service',
    'btn-services-configuration':'Configuration des services',
    'btn-services-configuration-required':'Configuration du service obligatoire',
    'btn-dealer-proposal':'Les propositions de modifications concessionaire',
    'btn-required':'Obligatoire',
    'btn-commission-level':'Communiqué de retour',
    'btn-submission-process-configuration':'Configuration de processus de soumission',
    'btn-proposal-update':'Proposition de mise a jour',
    'btn-news-administration':'Administration nouvelles',
    'btn-promotional-images':'Images promotionnelles',
    'lb-promotional-images':'Images promotionnelles',
    'btn-models':'Modèles',
    'msg-image-size':'L\'image doit avoir les dimensions minimales de 1024x435 px et la taille maximum de 8mo.',
    'lb-select-brand':'Sélectionnez la marque',
    'msg-error-extension':'Ils ne sont autorisés des fichiers avec les extensions suivantes',
    'msg-error-max-size':'L\'image doit avoir une taille maximale de 8mo.',
    'msg-sucesso-save-image':'Image enregistrée avec succès.',
    'msg-sucesso-remove-image':'L\'image avec succès enlevé.',
    'msg-info-select-financi-brand':'Vous devez sélectionner une marque financière.',
    'lb-avaliable-services':'Services disponibles',
    'lb-avaliable-service':'Service disponible',
    'lb-service-unavaliable':'Service non disponible',
    'lb-dealerships':'Concessionnaires',
    'lb-avaliable':'Disponible',
    'lb-not-avaliable':'Non disponible',
    'lb-mandatory-services':'Services requis',
    'lb-required':'Obligatoire',
    'lb-not-required':'En option',
    'lb-check-with-RCI-comercial-consultant':'Vérifiez auprès du représentant commercial rci',
    'lb-brand':'Marque',
    'btn-choose-file':'Choisissez fichier',
    'btn-remove':'Supprimer',
    'lb-vehicle-band':'Marque du véhicule',
    'lb-vehicle-model':'Modèle du véhicule',
    'lb-vehicle-version':'Version du véhicule',
    'lb-version':'Version',
    'msg-image-size-modelo':'Image avec taille au permis. \ n choisissez un fichier plus petit que 2 mo',
    'msg-images-registered-brand':'Aucune image enregistré pour la marque',
    'msg-images-registered-model':'Aucune image enregistré au modèle',
    'msg-images-registered-version':'Aucune image enregistrées pour la version',
    'update-button-behavior-configuration':'Comportement réglage du bouton actualiser',
    'lb-welcome':'Bienvenue',
    'lb-connected-by':'Connecté en tant que',
    'lb-back-your-profile':'Retour au profil',
    'btn-search':'Recherche',
    'btn-reset':'Redéfinir',
    'btn-enter':'Entrer',
    'lb-proposal-number':'Le numéro de proposition',
    'lb-customer-type':'Type de client',
    'btn-logout':'Laisser',
    'btn-send':'Envoyer',
    'lb-my-agreements':'Mes propositions',
    'lb-client-type':'Type de client',
    'lb-status-proposal':'Statut proposition',
    'lb-date-initial-creation':'Accueil date de création',
    'lb-date-final-creation':'Date de création finale',
    'lb-date-initial-validate':'Date de début de validité',
    'lb-date-final-validate':'Date d\'expiration finale',
    'lb-dealership':'Concession',
    'lb-exemption':'Exemption',
    'lb-with':'Avec',
    'lb-of':'De',
    'lb-custumer-personal-data':'Données de personnel client',
    'lb-cpf-cnpj':'Cpf ou cnpj',
    'lb-client-name':'Nom du client',
    'lb-contact-information':'Détails de contact',
    'lb-phone-number':'Téléphone client',
    'lb-localization':'Emplacement',
    'lb-state':'Etat',
    'lb-select-state':'Sélectionnez un état',
    'lb-simulation-information':'Information simulation',
    'btn-choose-vehicle':'Choisissez véhicule',
    'lb-brands':'Marques',
    'lb-simulate':'Simuler',
    'lb-model':'Modèle',
    'lb-national':'National',
    'lb-imported':'Importé',
    'lb-create-by':'Créé par',
    'lb-creation-date':'Date de création',
    'lb-financial-brands':'Marques financières',
    'lb-publish':'Publier',
    'btn-save-news':'Enregistrer nouvelles',
    'lb-list-of-registered-news':'La liste des nouvelles enregistrée',
    'lb-new-title':'Titre nouvelles',
    'lb-actions':'Actes',
    'lb-commission-level':'Communiqué de retour',
    'lb-vendor-manager':'Vendeur / responsable',
    'lb-select-a':'Sélectionnez un',
    'lb-product':'Produit',
    'lb-select-return':'Sélectionnez retour',
    'lb-release':'Libération',
    'btn-release':'Libération',
    'lb-release-date':'Date de sortie',
    'lb-fleet-code':'Code flotte',
    'lb-commission-level-date':'Date de sortie',
    'lb-release-by':'En libérant',
    'lb-released-level':'Retour sortie',
    'lb-validate':'Validité',
    'lb-proposal':'Proposition',
    'lb-salesman':'Vendeur',
    'lb-dealer-proposal':'Les propositions de modifications concessionaire',
    'lb-client':'Client',
    'lb-status':' statut',
    'lb-financed':'Par capitalisation',
    'lb-table':'Table',
    'lk-reassign':'Retour',
    'lb-detailing':'Détails',
    'lb-reassign':'Retour',
    'btn-reassign':'Réassigner',
    'lb-amount-financed':'Montant financé',
    'lb-validate-date':'Validité des données',
    'lb-previous-concessionaire':'Concession précédente',
    'lb-new-concessionaire':'Nouvelle concession',
    'lb-the-proposal-number':'Le numéro de la proposition',
    'lb-name':'Nom',
    'lb-simulation-print':'Imprimer',
    'btn-simulation-print':'Imprimer',
    'text-warning-conjugue':'Vous avez sélectionné les données de qualité de parantesco « conjoint / partenaire » avec ces données de client conjoint seront copiés sur le garant 1 et toutes les modifications seront répliquées entre les deux ecrans. Vous confirmez le degré de parenté?',
    'lb-model-selected':'Modèle sélectionné',
    'lb-vehicle-value':'Valeur du véhicule',
    'lb-optional':'En option',
    'lb-accessories':'Accessoires',
    'lb-accessorie':'Accessoire',
    'lb-value':'Valeur',
    'lb-subtotal-options':'Sous-total en option',
    'lb-subtotal-accessories':'Accessoires sous-total',
    'lb-total':'Total',
    'lb-vehicle':'Véhicule',
    'lb-manufacturing-year':'Année de construction',
    'lb-model-year':'Modèle année',
    'lb-vehicle-type':'Type de véhicule',
    'lb-value-car':'Valeur de la voiture',
    'lb-total-value':'Valeur totale',
    'lb-review-connected-simulation':'Examen de simulation trouvé',
    'lb-financial-type':'Source de financement',
    'lb-lack':'Pénurie',
    'lb-entrance':'Entrée',
    'lb-financial-during':'Durée du financement',
    'lb-contracted-services':'Services contractuels',
    'lb-financial-protection-insurance':'Protection financière sécurisée',
    'lb-safe-tranquility':'Assurer la paix',
    'lb-safe-auto':'Assurance auto',
    'lb-monthly':'Mensuel',
    'lb-total-financial':'Total des financimento',
    'lb-edit-vehicle':'Modifier le véhicule',
    'lb-custumer-card':'Spécifications des clients',
    'lb-installments':'Parcelles',
    'lb-payment-plan':'Plan de paiement',
    'lb-call-condition':'Etat appel',
    'lb-services':'Entretien',
    'lb-and':'Et',
    'lb-insurance':'Assurance',
    'lb-see-services-and-insurance':'Voir les services et les assurances',
    'lb-total-funded':'Financement total',
    'lb-custumer-rate':'Taux client',
    'lb-contract':'Louer',
    'lb-simulation':'Simulation',
    'lb-add-new':'Ajouter un',
    'btn-see-services-and-insurance':'Voir les services et les assurances',
    'lb-insert-optionals-and-accessories':'Options d\'insertion et accessoires',
    'lb-custumer-data':'Les données des clients',
    'btn-edit-information':'Modifier les informations',
    'lb-residential-data':'Données résidentielles',
    'lb-spouse':'Epoux',
    'lb-professional-data':'Informations professionnelles',
    'lb-personal-references':'Les références personnelles',
    'lb-bank-data':' coordonnées bancaires',
    'lb-custumer-edit':'Modifier le client',
    'lb-proposal-history':'Histoire de la proposition',
    'lb-comercial-phone-number':'Téléphone professionnel',
    'msg-invalid-cpf-cnpj':'Champ cpf / cnpj invalide',
    'msg-invalid-email':'Champ incorrect e-mail',
    'lb-number':'Nombre',
    'lb-address':'Adresse',
    'lb-complement':'Complément',
    'lb-neighborhood':'Quartier',
    'lb-city':'Ville',
    'lb-citizenship':'Citoyenneté',
    'lb-naturalness':'Nationalité',
    'lb-type-of-residence':'Type de résidence',
    'lb-lives-in-address-since':'Réside a l\'adresse indiquée',
    'lb-mailing-address':'Adresse postale',
    'lb-bank':'Banque',
    'lb-code-bank':'Code banque',
    'lb-agency':'Agence',
    'lb-checking-account':'Compte courant',
    'lb-custumer-since':'Client depuis',
    'lb-type-account':'Type de compte',
    'lb-phone-agency':'Agence telelefone',
    'btn-vehicle-data':'Données de la machine',
    'lb-gender':'Sexe',
    'lb-date-of-birth':'Date de naissance',
    'lb-marital-status':'Etat civil',
    'lb-residencial-number':'Résidences de téléphone',
    'lb-phone-type':'Type de téléphone',
    'lb-cel-phone':'Téléphone portable',
    'lb-nationality':'Nationalité',
    'lb-person-politically-exposed':'Personne politiquement exposées',
    'lb-education-degree':'Diplôme institution',
    'lb-physical-deficiency':'Handicap physique',
    'lb-name-of-the-father':'Nom du père',
    'lb-name-of-the-mother':'Nom de la mère',
    'lb-document-type':'Type de document',
    'lb-document-number':'Numéro du document',
    'lb-document-country':'Pays de document',
    'lb-uf-document':'Document uf',
    'lb-emission-date':'Date d\'émission',
    'lb-issuing-board':'Organe emetteur',
    'lb-company-name':'Nom de l\'entreprise',
    'lb-legal-nature':'Nature juridica',
    'lb-telephone':'Téléphone',
    'lb-telephone-extension':'Branche',
    'lb-open-date':'Date d\'ouverture',
    'lb-company-size':'Taille de l\'entreprise',
    'lb-head-office':'Siège propres',
    'lb-monthly-billing':'Facturation mensuelle',
    'lb-groups-activity-economic':'Groupes d\'activité economique',
    'lb-activity-economic':'L\'activité economique',
    'btn-residential-data':'Données résidentielles',
    'lb-lives-in-address-from':'Réside à l\'adresse indiquée',
    'btn-personal-references':'Les références personnelles',
    'lb-full-name':'Nom et prénom',
    'btn-banking-reference':'Référence bancaire',
    'lb-occupation':'Occupation',
    'lb-role':'Fonction',
    'lb-office':'Bureau',
    'lb-comercial-phone':'Téléphone professionnel',
    'lb-size-company':'Affranchissement',
    'lb-admission-date':'Date d\'admission',
    'lb-patrimony':'Patrimoine',
    'lb-type-of-income':'Type de revenu',
    'lb-type-of-income-report':'Type de preuve de revenu',
    'lb-monthly-income':'Revenu mensuel',
    'lb-others-icome':'Autres revenus',
    'lb-cellphone':'Téléphone portable',
    'lb-agency-phone-number':'Agence téléphone',
    'btn-professional-data':'Informations professionnelles',
    'lb-chassis-number':'Numéro de châssis',
    'lb-register-number':'Numéro d\'enregistrement',
    'lb-registration-province':'État d\'immatriculation',
    'lb-licensing-province':'Licences d\'état',
    'lb-color':'Couleur',
    'lb-origin':'Source',
    'btn-guarantor':'Garant',
    'lb-vehicle-data':'Données de la machine',
    'lb-credit-report':'Avis de crédit',
    'lb-actor':'Acteur',
    'lb-date':'Date',
    'lbl-vehicle':'Véhicule',
    'lbl-input-value':'La valeur d\'entrée',
    'lbl-plot-amount':'Part de la valeur',
    'lbl-customer-contacts':'Les contacts clients',
    'lbl-email':'E-mail',
    'btn-return-shipping':'Retour a la navigation',
    'btn-available-documentation':'Documentation disponible',
    'lb-description':'Description',
    'btn-print':'Imprimer',
    'btn-back-to-custumer-card':'Retour au formulaire client',
    'lb-choose-brand-new-one':'Sélectionnez la marque d\'un seminovo',
    'lb-choose-model':'Choisissez un modèle',
    'lb-choose-version':'Choisissez la version',
    'lb-choose-model-year':'Choisissez l\'année modèle',
    'lb-price-base':'Prix ​​de base',
    'lb-direct-sale':'La vente directe',
    'lb-show-room':'Salle d\'exposition',
    'lb-new-ones':'Concessionnaires',
    'lb-sale-type':'Type de vente',
    'btn-simulation':'Simulation',
    'lb-select-profile':'Sélectionnez un profil',
    'lb-dealership-code':'Code concessionnaire',
    'lb-close':'Près',
    'lb-dont-exempt-registration-fee':'Non exemptés frais d\'inscription',
    'lb-exempt-customer-registration-fee':'Frais d\'inscription client exonéré',
    'lb-send':'Expédition',
    'lb-yes':'Oui',
    'lb-no':'Pas',
    'lb-submission-process-configuration':'Configuration du processus de soumission',
    'lb-select-type-change':'Sélectionnez un type de changement',
    'lb-authorized':'Autorisé',
    'lb-not-authorized':'Non autorisée',
    'msg-sucesso-save':'Enregistré avec succès.',
    'lb-required-field':'Champ obligatoire',
    'simulation-windows':'Windows simulation',
    'windows':'Fenêtres',
    'language':'Langue',
    'change-password2':'Mot de passe',
    'logout2':'Exit',
    'msg_invalid_login':'Utilisateur ou mot de passe incorrect',
    'msg_inative_user':'Utilisateur inactif. Contactez concessionnaire administrateur',
    'msg_login_success':'Connectez-vous organisé avec succès',
    'msg-invalid-token':'Invalide jeton. Demander un nouveau mot de passe changement',
    'msg-invalid-user-email':'Utilisateur / e-mail ne correspond pas a la base de données enregistrée dans la',
    'msg-new-passwords-doesnt-check':'Nouveau mot de passe et une nouvelle confirmation de mot de passe ne correspondent pas',
    'msg-password-validation':'Le nouveau mot de passe doit comporter au moins un caractère numérique. Au moins un caractère alphanumérique',
    'msg-send-mail-success':'Courriel envoyé avec succès',
    'msg-new-password-must-be-equal':'Les nouveaux mots de passe doivent correspondre',
    'msg-new-password-must-be-different-old-one':'Le nouveau mot de passe doit etre différent du mot de passe actuel',
    'msg-current-password-incorrect':'Mot de passe actuel incorrect',
    'msg-change-password-success':'Mot de passe changé avec succès',
    'No-dealerships-to-profile':'Aucun concessionnaire pour le filtre indiqué',
    'no-salesman-to-dealership':'Il y a des vendeurs pour le concessionnaire sélectionné',
    'lb-change-date':'Date du changement',
    'lb-proposal-adp-number':'Non mouvement adp',
    'lb-read':'Lire',
    'lbl-aviso':'Lien de confirmation entre le client et le garant?',
    'lb-contract-selected-services':'Location de services sélectionnés',
    'msg-bad-request-service-santander':'Le service est temporairement indisponible essayer a nouveau en quelques secondes.',
    'msg-bad-request-service-s3':'Le service est temporairement indisponible essayer a nouveau en quelques secondes.',
    'msg-doc-generated':'Document généré avec succès.',
    'msg-error-send-email':'Erreur d\'envoi par courriel.',
    'msg-error-generated-doc':'Erreur lors de la préparation de la documentation.',
    'common-msg-maintenance':'Fonctionnalité de maintenance',
    'common-msg-unavailable':'Pas actuellement disponible',
    'msg-worn-session-expired-401':'La session a expiré.',
    'lb-repackage':'Forfait',
    'lb-delay':'Manque',
    'lb-entrance-value':'Valeur d\'entrée',
    'lb-entrance-percent':'% d\'entrée',
    'lb-contracted':'Contracté',
    'lb-contracted-sub':'Cliquez pour continuer',
    'lb-residential-data_guarantor_1':'Resident Data Guarantor 1',
    'lb-residential-data_guarantor_2':'Garantie des données sur la résidence 2',
    'msg-send-santander-confirmation':'Voulez-vous soumettre cette proposition pour l\'analyse de crédit?',
    'lb-uf':'UF',
    'lb-branch':'Agence',
    'lb-digit':'Chiffre',
    'lb-account':'Vérification du compte',
    'lb-phone-branch':'Téléphone de l\'agence',
    'lb-of-document':'du document',
    'lb-country':'Les parents',
    'no-delaerships-to-profile':'Aucun concessionnaire pour le filtre indiqué',
    'btn-vehicle':'Véhicule',
    'lb-edit-simulation':'Modifier la simulation',
    'lb-edit-customer-card':'Modifier la fiche client',
    'lb-resum':'Résumé',
    'btn-fill-customer-card':'Remplissez le formulaire client',
    'lb-review-contracted-simulation':'Examiner la simulation contractuelle',
    'lb-compare':'Comparer',
    'lb-months':'des mois',
    'lb-days':'jours',
    'lb-name-certified-agent':'Nom de l\'agent certifié',
    'lb-certified-number':'Numéro de certificat',
    'lb-certified-valid-date':'Certificat de validité de date',
    'btn-validate-proposal':'Valider la proposition',
    'lb-submission':'Soumission',
    'btn-customer-data':'Données client',
    'btn-contract-service':'Services contractuels',
    'lb-guarantor-data':'Détails du garant',
    'lb-guarantor':'Garant',
    'lb-banking-references':'Références',
    'lb-back-to-customer-card':'Retour au formulaire client',
    'lb-back-to-send':'Retour à l\'expédition',
    'tab-utility-car':'Outils',
    'tab-car':'Voiture',
    'lb-edit-customer':'Modifier le client',
    'lb-customer-data':'Données client',
    'btn-send-proposal':'Envoyer une proposition',
    'lb-select-guarantor-type':'Sélectionnez un type de garant',
    'lb-type-of-relationship-company':'Type de relation',
    'lb-degree-of-kinship':'Degré de parenté',
    'lb-guarantor-type':'Type de garant',
    'btn-spouse':'Conjoint',
    
};